name: 'Docker Action'
description: 'Docker example action'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: '....'
  say-something:
    description: 'Optional thing to say'
    required: false
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.say-something }}
