
name: example action

on:
  workflow_dispatch:

jobs:
  docker-action-example:
    runs-on: ubuntu-latest
    name: my docker example
    steps:
      - name: Hello action
        id: hello
        uses: j-dunham/docker-action-example@v3.2
        with:
          who-to-greet: "Sun"
          say-something: "What"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Hello actions with no args
        id: no-args
        uses: j-dunham/docker-action-example@v3.2
      - name: Get no args output
        run: echo "No args time was ${{ steps.no-args.output.time }}"
